pipeline {
    agent any
    
    environment {
        AWS_REGION = 'us-east-1'
        ECR_URL = '781013578291.dkr.ecr.us-east-1.amazonaws.com/81117/orders-api'
        AWS_ACCOUNT_ID = '781013578291'
        IMAGE_TAG = "${BUILD_NUMBER}"
        FULL_IMAGE = "${ECR_URL}:${IMAGE_TAG}"
    }
    
    stages {
        stage('Clean WS') {
            steps {
                deleteDir()
            }
        }
        
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/3nu3l/proyecto-aws-devops-81117.git'
            }
        }
        
        stage('Build Image') {
            steps {
                sh "docker build . -t ${FULL_IMAGE} -t ${ECR_URL}:latest"
            }
        }
        
        stage('Tests') {
            steps {
                sh "docker run --rm ${FULL_IMAGE} pytest tests"
            }
        }
        
        stage('Login & Push to ECR') {
            steps {
                sh """
                aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
                docker push ${FULL_IMAGE}
                docker push ${ECR_URL}:latest
                """
            }
        }
        stage('Update Helm Values') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'github-app-81117', 
                                passwordVariable: 'GIT_PASSWORD', 
                                usernameVariable: 'GIT_USERNAME')]) {
                    script {

                        sh """
                        rm -rf helm-repo
                        git clone https://github.com/3nu3l/proyecto-aws-devops-81117-helm.git
                        """
                        
                        dir('helm-repo') {
                            sh "sed -i 's/tag: .*/tag: \"${IMAGE_TAG}\"/' values.yaml"
                            
                            sh """
                                git config user.email "jenkins@81117.com"
                                git config user.name "Jenkins CI"
                                git add values.yaml
                                git commit -m "Update image tag to ${IMAGE_TAG}"
                                git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/3nu3l/proyecto-aws-devops-81117-helm.git main
                            """
                        }
                    }
                }
            }
        }
    }
}